version: '3.7'

volumes:
  dependency-track:

services:
  dtrack-apiserver:
    image: dependencytrack/apiserver
    environment:
      EXTRA_JAVA_OPTIONS: "-Xmx4G"
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8081:8080'
    volumes:
      - 'dependency-track:/data'
      - "./cacerts:/opt/java/openjdk/lib/security/cacerts:ro"
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=https://ec2-35-171-179-116.compute-1.amazonaws.com:443
    ports:
      - '8080:8080'
    restart: unless-stopped

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    depends_on:
      - dtrack-apiserver
      - dtrack-frontend
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx-selfsigned.crt:/opt/ssl/dt_server.crt"
      - "./nginx/nginx-selfsigned.key:/opt/ssl/dt_server.key"
    ports:
      - '443:443'
    restart: unless-stopped
